### ISSUE TITLE
Release date?  need bug fix pushed

### ISSUE THREAD

**Issue by jonathan-nye** [bitzesty/devise_zxcvbn#18]
@matthewford, do you have an ETA on releasing the latest updates?  The bug that was fixed in #17 is a show-stopper for us.  If it is not ready, can you push a patch with just that commit?  Thanks!

**Comment by matthewford** [comment]
@jonathan-nye pushed `2.1.1`

**Comment by jonathan-nye** [comment]
great...thanks @matthewford !!
