### ISSUE TITLE
Strategy for dynamic min_password_score

### ISSUE THREAD

**Issue by lanceonken** [bitzesty/devise_zxcvbn#19]
I'd like to have `config.min_password_score = 3` but require a higher score of 4 for Users with admin access. Is there a strategy for a User instance to conditionally override min_password_score?

**Comment by matthewford** [comment]
I like this idea a lot, will put this on the backlog.

**Comment by matthewford** [comment]
@lanceonken you can do this by defining `min_password_score` in your admin class e.g.

https://github.com/bitzesty/qae/pull/997/files#diff-6488a177f01fa579fcc6bf24df50fce4L32
