### ISSUE TITLE
Skip scoring if model has other errors.

### ISSUE THREAD

**Issue by msumit** [bitzesty/devise_zxcvbn#21]
It would be better if zxcvbn doesn't append password score related errors, when the model has other validation errors already. For e.g. errors like this `Password can't be blank. Password not strong enough. It scored 0. It must score at least 2.` doesn't make any sense.

**Comment by klebershimabuku** [comment]
I do agree.

**Comment by matthewford** [comment]
@msumit Thanks, closed by version 2.1.2

**Comment by jalada** [comment]
I understand the rationale, but it's somewhat unexpected behaviour to have errors 'appear' once all the others have gone, and I think it would be good to have this documented somewhere.
