### ISSUE TITLE
ExecJS::ProgramError

### ISSUE THREAD

**Issue by handcrab** [bitzesty/devise_zxcvbn#23]
Hello, 
I'm using a sidekiq job to generate a temp password. But quite often I get `ExecJS::ProgramError: ExecJS::ProgramError` error while checking the strength of generated password. The error message is not very informative, but I guess the devise_zxcvbn / zxcvbn-js causes it.

Any ideas what could be wrong?

```
devise_zxcvbn (2.1.1)
  zxcvbn-js (~> 4.2.0)

def weak_password?(password)
  Devise.zxcvbn_tester.test(password, []).score < Devise.min_password_score
end

ExecJS.runtime.name #=> "therubyracer (V8)"
```

**Comment by IlkhamGaysin** [comment]
@handcrab Could you please show me your `Gemfile.lock` I am interested in a version of `therubyracer`

**Comment by IlkhamGaysin** [comment]
![2017-03-29 12 31 45](https://cloud.githubusercontent.com/assets/17009998/24448109/bb2ecc44-147b-11e7-9399-20aab23575bd.png)

I've tried to run this with these gems and it works. I guess I have to set the same version of `therubyracer` and `zxcvbn-js`...
```
therubyracer (0.12.2)
  libv8 (~> 3.16.14.0)
  ref
zxcvbn-js (4.4.2)
  execjs
```

**Comment by dreamfall** [comment]
@handcrab I could not reproduce the issue with following versions
```
    devise_zxcvbn (2.1.1)
      devise
      zxcvbn-js (~> 4.2.0)
    rails (5.0.2)
    sidekiq (2.17.6)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
```

Can you please provide with more info on the versions of the gems and/or the sample application where the error can be reproduced?

```ruby 
class User
  def weak_password?(password)
    Devise.zxcvbn_tester.test(password, []).score < Devise.min_password_score
  end
end

class HardWorker
  include Sidekiq::Worker
  def perform
    puts User.new.weak_password?("123")
  end
end
```
```
irb(main):009:0> HardWorker.perform_async
2017-03-29T15:19:18Z 9522 TID-ovzi54q3o INFO: Sidekiq client with redis options {}
=> "74826ba2d48b195a20495197" 
```
