### ISSUE TITLE
Can't call zxcvbn js function

### ISSUE THREAD

**Issue by cchandler81** [bitzesty/devise_zxcvbn#29]
I'm working on a client-side strength meter but when I attempt to call the zxcvbn function I get a not defined error in the console. If I add //= require zxcvbn to my application.js file I get a 

> couldn't find file 'zxcvbn' with type 'application/javascript' 

error. zxcvbn.js definitely exists in .rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/zxcvbn-js-4.4.3/data. What am I missing?

**Comment by matthewford** [comment]
Interesting, I'm primarily using this fo backend validation and using the normal zxcvbn.js for the client side.

**Comment by cchandler81** [comment]
I had a feeling that was the case. I was just hoping to be able to include the packaged version in the asset pipeline to both avoid duplication and ensure the same results on both sides.

**Comment by matthewford** [comment]
That is a good idea - something I will look into.

**Comment by matthewford** [comment]
closing this as we've switched to zxcvbn-rb
