### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by greyblake** [bitzesty/devise_zxcvbn#35]
Hey!
Thanks for the nice gem.

Do you have any plans to release a new version with conditional method `check_password_complexity?`

It looks like the current one on rubygems (4.4.1) uses `password_requires?`
It would be nice to have a new version with this change: https://github.com/bitzesty/devise_zxcvbn/commit/f59207d5a1ab548248a512c24348b1d0a3f2cd49

Thanks in advance!

**Comment by matthewford** [comment]
Thanks, released v5

**Comment by greyblake** [comment]
Wow! Thank you!!!
